name: json_scribe
description: "json scribe"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flex_color_scheme: ^8.0.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/

  # fonts:
  #   - family:
  #     fonts:
  #       - asset:
